ARG BASE_IMAGE=ghcr.io/statens-pensjonskasse/zulu-openjdk:25-jdk
FROM ${BASE_IMAGE}

ARG PACKAGE_MANAGER=microdnf
ARG MAVEN_VERSION="3.9.11"
ARG EXTRA_PACKAGES=""

USER root

RUN ${PACKAGE_MANAGER} install -y \
        curl \
        fontconfig \
        git-core \
        tar \
        wget \
        which \
        ${EXTRA_PACKAGES} \
    && ${PACKAGE_MANAGER} clean all \
    && rm -rf /var/cache/yum

# Må av en ukjent grunn kjøre `gzip -d` manuelt før utpakking med `tar -xvf` for arm64-image.
# Kun `tar -zxvf` fører til feilen `tar: Child returned status 1`
RUN curl -sSL -O "https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz" &&\
    gzip -d "apache-maven-${MAVEN_VERSION}-bin.tar.gz" &&\
    tar -xvf "apache-maven-${MAVEN_VERSION}-bin.tar" -C "/opt" &&\
    rm "apache-maven-${MAVEN_VERSION}-bin.tar" &&\
    rm -f "/opt/apache-maven-${MAVEN_VERSION}/conf/settings.xml" &&\
    ln -s "/opt/maven-settings/settings.xml" "/opt/apache-maven-${MAVEN_VERSION}/conf/settings.xml" &&\
    alternatives --install "/usr/bin/mvn" mvn "/opt/apache-maven-${MAVEN_VERSION}/bin/mvn" 2000

RUN ln -s "/opt/apache-maven-${MAVEN_VERSION}" "/opt/apache-maven-latest3"

USER app
