ARG BASE_IMAGE=ghcr.io/statens-pensjonskasse/rockylinux:9-minimal
FROM ${BASE_IMAGE}

ARG JAVA_VERSION=21
ARG JAVA_TYPE=jdk
ARG PACKAGE_MANAGER=microdnf
ARG PACKAGE_MANAGER_FLAGS="--assumeyes --nodocs --setopt=install_weak_deps=0"

USER root

RUN curl -sSL -O https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm \
    && rpm -ivh ./zulu-repo-1.0.0-1.noarch.rpm \
    && rm -f zulu-repo-1.0.0-1.noarch.rpm

RUN ${PACKAGE_MANAGER} ${PACKAGE_MANAGER_FLAGS} install \
    zulu${JAVA_VERSION}-ca-${JAVA_TYPE}-headless && \
    ${PACKAGE_MANAGER} clean all && \
    rm -rf /var/cache/yum

ENV JAVA_HOME=/usr/lib/jvm/zulu${JAVA_VERSION}

# Change truststore to include SPK root CA
RUN rm -f ${JAVA_HOME}/lib/security/cacerts && \
    ln -s /etc/pki/java/cacerts ${JAVA_HOME}/lib/security/cacerts

USER app
