ARG BASE_IMAGE=ghcr.io/statens-pensjonskasse/rockylinux:9-minimal
FROM ${BASE_IMAGE}

ARG JAVA_VERSION=21
ARG JAVA_TYPE=jdk
ARG PACKAGE_MANAGER=microdnf
ARG PACKAGE_MANAGER_FLAGS="--assumeyes --nodocs --setopt=install_weak_deps=0"

RUN ${PACKAGE_MANAGER} ${PACKAGE_MANAGER_FLAGS} install \
    zulu${JAVA_VERSION}-ca-${JAVA_TYPE}-headless && \
    ${PACKAGE_MANAGER} clean all && \
    rm -rf /var/cache/yum

ENV JAVA_HOME=/usr/lib/jvm/zulu${JAVA_VERSION}

# Change truststore to include SPK root CA
RUN rm -f ${JAVA_HOME}/lib/security/cacerts && \
    ln -s /etc/pki/java/cacerts ${JAVA_HOME}/lib/security/cacerts

RUN adduser app

USER app
WORKDIR /home/app
