ARG BUILDKIT_IMAGE_TAG="master"
FROM cr.spk.no/docker-hub/moby/buildkit:${BUILDKIT_IMAGE_TAG}-rootless

USER root

# Fetch and install current and previous root certificate from yum server
ADD --chmod=644 https://yum.spk.no/pub/pki/spk-root-ca-current.pem /usr/local/share/ca-certificates/
ADD --chmod=644 https://yum.spk.no/pub/pki/spk-root-ca-previous.pem /usr/local/share/ca-certificates/
RUN apk --no-cache update && \
    apk --no-cache add ca-certificates && \
    update-ca-certificates

USER user
