name: Build Rocky Linux 9 container image

on:
  push:
    branches:
      - main
      - build_image
  pull_request:
    branches:
      - main

jobs:
    build-and-publish:
      name: Build Rocky Linux container image
      runs-on: self-hosted
      permissions:
        contents: read
        packages: write
      env:
        TZ: Europe/Oslo
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
          with:
            fetch-depth: 0

        - name: Build with Docker
          run: |
            podman buildx build \
              --file os/Containerfile \
              --build-arg-file os/rocky-linux-9-minimal.conf \
              --sbom=true \
              --tag ghcr.io/statens-pensjonskasse/rockylinux:9-minimal \
              --platform linux/amd64

        - name: Login to GitHub Container Registry
          run: |
            echo "${{ github.token }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Push to GitHub Container Registry
          run: |
            podman push ghcr.io/statens-pensjonskasse/rockylinux:9-minimal
