name: Build BuildKit container image

on:
  push:
    branches:
      - main
      - build_image
  pull_request:
    branches:
      - main

jobs:
    build-and-publish:
      name: Build BuildKit container image
      runs-on: self-hosted
      permissions:
        contents: read
        packages: write
      env:
        TZ: Europe/Oslo
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
          with:
            fetch-depth: 0

        - name: Build with Docker
          run: |
            podman buildx build \
              --file buildkit/Containerfile \
              --sbom=true \
              --tag ghcr.io/statens-pensjonskasse/buildkit:spk \
              --platform linux/amd64,linux/arm64

        - name: Push to GitHub Container Registry
          run: |
            podman push \
              --authfile ~/.docker/config.json \
              ghcr.io/statens-pensjonskasse/buildkit:spk
